import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>

      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/favoriteproduct"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            FavoriteProduct
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/salesshop"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SalesShop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/createproduct"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CreateProduct
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/homepage"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/product"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Product
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/productdetail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ProductDetail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/payment"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Payment
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/ordertracking"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            OrderTracking
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/profile"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Profile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/customerlayoutofshop"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CustomerLayoutOfShop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/listofshop"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ListOfShop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blog" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Blog
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/blogdetail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            BlogDetail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/contact"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Contact
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/customercare"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CustomerCare
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/login"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Login
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/mailbox"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Mailbox
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/chatbox"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Chatbox
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/dashboardadmin"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            DashboardADMIN
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/ordermanagement"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            OrderManagement
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/clientmanagementadmin"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ClientManagementAdmin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/register"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Register
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/order"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Order
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/shoplayout"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            ShopLayout
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/policy"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Policy
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/cartdetail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CartDetail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/paymentsuccess"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            PaymentSuccess
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/compareproducts"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            CompareProducts
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/dashboard"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            Dashboard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/salesmanager"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            SalesManager
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
